channels:
- conda-forge
dependencies:
- python=3.12.3
- pip<=24.3.1
- pip:
  - mlflow==2.17.2
  - cloudpickle==3.1.0
  - imbalanced-learn==0.12.4
  - numpy==2.1.3
  - pandas==2.2.3
  - psutil==6.1.0
  - scikit-learn==1.5.2
  - scipy==1.14.1
  - xgboost==2.1.2
name: mlflow-env
